name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh-agent.sock
    steps:
    - name: Install Packages
      run: |
        sudo apt-get update
        sudo apt-get install libpam0g-dev libssl-dev
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        ssh-agent -a $SSH_AUTH_SOCK
        ssh-keygen -t ecdsa -b 521 -f $HOME/.ssh/id_ecdsa521
        ssh-keygen -t ecdsa -b 384 -f $HOME/.ssh/id_ecdsa384
        ssh-keygen -t ecdsa -b 256 -f $HOME/.ssh/id_ecdsa256
        ssh-keygen -t ed25519 -f $HOME/.ssh/id_ed25519
        ssh-keygen -t rsa -f $HOME/.ssh/id_rsa
        ssh-keygen -t dsa -f $HOME/.ssh/id_dsa
        ssh-add $HOME/.ssh/id_ecdsa521
        ssh-add $HOME/.ssh/id_ecdsa384
        ssh-add $HOME/.ssh/id_ecdsa256
        ssh-add $HOME/.ssh/id_ed25519
        ssh-add $HOME/.ssh/id_rsa
        ssh-add $HOME/.ssh/id_dsa
        cp $HOME/.ssh/id_rsa.pub $HOME/.ssh/authorized_keys
        cargo test --verbose
    - name: Build Release
      run: cargo build --release
    - name: Package Debian
      run: |
        mkdir -p debian/lib/x86_64-linux-gnu/security/
        cp target/release/libpam_rssh.so debian/lib/x86_64-linux-gnu/security/
        mkdir -p debian/DEBIAN
        echo "Package: libpam-rssh" > debian/DEBIAN/control
        echo "Version: 1.1.0" >> debian/DEBIAN/control
        echo "Section: base" >> debian/DEBIAN/control
        echo "Priority: optional" >> debian/DEBIAN/control
        echo "Architecture: amd64" >> debian/DEBIAN/control
        echo "Maintainer: Your Name <your.email@example.com>" >> debian/DEBIAN/control
        echo "Description: This PAM module provides ssh-agent based authentication." >> debian/DEBIAN/control
        dpkg-deb --build debian
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: libpam-rssh
        path: debian.deb
